whitelist_rules:
    - block_based_kvo
    - closing_brace
    - closure_parameter_position
    - closure_spacing
    - colon
    - comma
    - conditional_returns_on_newline
    - control_statement
    - empty_count
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - fatal_error_message
      #- identifier_name
    - leading_whitespace
    - legacy_constructor
    - let_var_whitespace
    - literal_expression_end_indentation
    - mark
    - multiple_closures_with_trailing_closure
    - nesting
    - notification_center_detachment
    - opening_brace
    - operator_usage_whitespace
    - operator_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - private_unit_test
    - prohibited_super_call
    - protocol_property_accessors_order
    - redundant_nil_coalescing
    - redundant_optional_initialization
    - redundant_string_enum_value
    - redundant_void_return
    - return_arrow_whitespace
    - shorthand_operator
    - statement_position
    - superfluous_disable_command
    - switch_case_alignment
    - switch_case_on_newline
    - trailing_comma
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - type_name
    - unneeded_break_in_switch
    - unused_closure_parameter
    - unused_enumerated
    - unused_optional_binding
    - vertical_parameter_alignment
    - vertical_parameter_alignment_on_call
    - vertical_whitespace
    - void_return
    - weak_delegate

type_name:
  max_length:
    warning: 60
    error: 80
identifier_name:
  min_length:
    warning: 1

nesting:
    type_level:
        warning: 2

excluded:
    - Pods

reporter: "xcode"
